export const projects = [
  {
    id: 1,
    shortName: "O U A A A",
    longName: "Outil des Acteurs Alternatifs en Aunis",
    topic: "Web Development",
    roles: ["Fullstack Developer"],
    shortDescription: "Web application made to increase awareness around economic and associative players who reinvent our society to make it more resilient in the area of La Rochelle, France.\n\nWe are two developers coding the first version of the platform at the initiative of three collectives.",
    longDescription: "",
    siteGoal: "Accelerate the necessary change of our society by creating links between economic / associative players and general public.",
    devGoal: "First version development to have a functional platform.",
    features: [
      "Mapping of the different players",
      "Agenda of the events",
      "Date or category filters on the mapping and agenda",
      "Newsletter per event and per player",
      "Users and actors registration",
      "Admin panel to manage users, players, and events",
    ],
    stack: [
      {Backend: ["NodeJS", "GraphQL", "MySQL", "Docker"]},
      {Frontend: ["ReactJS", "NextJS", "Typescript", "Leaflet", "MaterialUI"]},
      {Devops: ["Docker", "GitLab"]},
    ],
    mainImage: "surf.png",
    diapoImages: ["", ""],
    otherImages: ["surf.png"],
    urlGithub: {
      server: "https://gitlab.acteursdelatransition.fr/acteurs-de-la-transition/serveur",
      client: "https://gitlab.acteursdelatransition.fr/root/acteursdelatransition",
    },
    urlWebsite: "https://ouaaa.org/",
  },
  {
    id: 2,
    shortName: "Coach Me",
    longName: "Coach Me",
    topic: "Web Development",
    roles: ["Backend Developer"],
    shortDescription: "Web application made to increase awareness around economic and associative players who reinvent our society to make it more resilient in the area of La Rochelle, France.\n\nWe were three backend developers working the first version of the platform.",
    longDescription: "",
    siteGoal: "Accelerate the necessary change of our society by creating links between economic / associative players and general public.",
    devGoal: "First version development to have a functional platform.",
    features: [
      "Mapping of the different players",
      "Agenda of the events",
      "Date or category filters on the mapping and agenda",
      "Newsletter per event and per player",
      "Users and actors registration",
      "Admin panel to manage users, players, and events",
    ],
    stack: [
      {Backend: ["Ruby", "Ruby on Rails", "PostgreSQL"]},
      {Frontend: ["HTML", "CSS", "Javascript", "Bootstrap"]},
      {Devops: ["Heroku", "GitHub"]},
    ],
    mainImage: "surf.png",
    diapoImages: ["", ""],
    otherImages: ["surf.png"],
    urlGithub: {
      server: "https://gitlab.acteursdelatransition.fr/acteurs-de-la-transition/serveur",
      client: "https://gitlab.acteursdelatransition.fr/root/acteursdelatransition",
    },
    urlWebsite: "https://ouaaa.org/",
  },
  {
    id: 3,
    shortName: "Bordeaux Event",
    longName: "Bordeaux Event",
    topic: "Web Development",
    roles: ["Backend Developer"],
    shortDescription: "Eventbrite type website to book and create all sorts of events.",
    longDescription: "",
    siteGoal: "Accelerate the necessary change of our society by creating links between economic / associative players and general public.",
    devGoal: "First version development to have a functional platform.",
    features: [
      "Mapping of the different players",
      "Agenda of the events",
      "Date or category filters on the mapping and agenda",
      "Newsletter per event and per player",
      "Users and actors registration",
      "Admin panel to manage users, players, and events",
    ],
    stack: [
      {Backend: ["Ruby", "Ruby on Rails", "PostgreSQL"]},
      {Frontend: ["HTML", "CSS", "Javascript", "Bootstrap"]},
      {Devops: ["Heroku", "GitHub"]},
    ],
    mainImage: "surf.png",
    diapoImages: ["", ""],
    otherImages: ["surf.png"],
    urlGithub: {
      server: "https://gitlab.acteursdelatransition.fr/acteurs-de-la-transition/serveur",
      client: "https://gitlab.acteursdelatransition.fr/root/acteursdelatransition",
    },
    urlWebsite: "https://ouaaa.org/",
  },
  {
    id: 4,
    shortName: "Memory Game",
    longName: "Memory Game",
    topic: "Web Development",
    roles: ["Backend Developer"],
    shortDescription: "Memory Game to have fun using ReactJS.",
    longDescription: "",
    siteGoal: "Accelerate the necessary change of our society by creating links between economic / associative players and general public.",
    devGoal: "First version development to have a functional platform.",
    features: [
      "Mapping of the different players",
      "Agenda of the events",
      "Date or category filters on the mapping and agenda",
      "Newsletter per event and per player",
      "Users and actors registration",
      "Admin panel to manage users, players, and events",
    ],
    stack: [
      {Backend: ["Ruby", "Ruby on Rails", "PostgreSQL"]},
      {Frontend: ["HTML", "CSS", "Javascript", "Bootstrap"]},
      {Devops: ["Heroku", "GitHub"]},
    ],
    mainImage: "surf.png",
    diapoImages: ["", ""],
    otherImages: ["surf.png"],
    urlGithub: {
      server: "https://gitlab.acteursdelatransition.fr/acteurs-de-la-transition/serveur",
      client: "https://gitlab.acteursdelatransition.fr/root/acteursdelatransition",
    },
    urlWebsite: "https://ouaaa.org/",
  },
];
